/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs.cs2263;

import org.gradle.testfixtures.ProjectBuilder;
import org.gradle.api.Project;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 * A simple unit test for the 'edu.isu.cs.cs2263.greeting' plugin.
 */
public class Skilldrill2PluginTest {
    @Test public void pluginRegistersATask() {
        // Create a test project and apply the plugin
        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("edu.isu.cs.cs2263.greeting");

        // Verify the result
        assertNotNull(project.getTasks().findByName("greeting"));
    }
}
